// ================== VIJANA ==================
export const vijana = [
  {
    id: 1,
    fullName: "Asha Mrema",
    email: "asha@gmail.com",
    phone: "0712345678",
    gender: "Female",
    educationLevel: "Bachelor",
    isActive: true,
    createdAt: "2025-06-01",
  },
  {
    id: 2,
    fullName: "Juma Said",
    email: "juma@gmail.com",
    phone: "0756781234",
    gender: "Male",
    educationLevel: "Diploma",
    isActive: false,
    createdAt: "2025-12-12",
  },
];

// ================== FURSA ==================
export const fursa = [
  {
    id: 1,
    title: "Web Development Internship",
    category: "Internship",
    location: "Dar es Salaam",
    deadline: "2024-12-31",
    applications: "Halmashali ya wilaya ya Mlele",
    status: "PUBLISHED",
    createdAt: "2025-06-10",
  },
  {
    id: 2,
    title: "Youth Entrepreneurship Grant",
    category: "Grant",
    location: "Dodoma",
    deadline: "2024-11-20",
    applications: "Halmashali ya wilaya ya Mlele",
    status: "DRAFT",
    createdAt: "2025-06-05",
  },
  {
    id: 3,
    title: "Youth Mechanicla Enginering Grant",
    category: "Grant",
    location: "Dodoma",
    deadline: "2024-11-20",
    applications: "Halmashali ya wilaya ya Mlele",
    status: "DRAFT",
    createdAt: "2025-06-05",
  },
];

// ================== MAFUNZO ==================
export const mafunzo = [
  {
    id: 1,
    title: "React for Beginners",
    type: "VIDEO",
    resourceUrl: "https://youtube.com",
    createdAt: "2025-06-02",
    category: "Technology",
    level: "Beginner",
    instructor: "John Mrema",
    startDate: "2024-07-01",
    endDate: "2024-09-30",
    status: "ONGOING",

  },
  {
    id: 2,
    title: "Full Stack Web Development",
    type: "VIDEO",
    resourceUrl: "https://youtube.com",
    createdAt: "2025-06-02",
    category: "Technology",
    level: "Beginner",
    instructor: "John Mrema",
    startDate: "2024-07-01",
    endDate: "2024-09-30",
    status: "ONGOING",
  },
  {
    id: 3,
    title: "Entrepreneurship Basics",
    type: "PDF",
    resourceUrl: "/files/proposal.pdf",
    createdAt: "2025-06-02",
    category: "Business",
    level: "Intermediate",
    instructor: "Mary Joseph",
    startDate: "2024-08-15",
    endDate: "2024-10-15",
    status: "UPCOMING",
  },
  {
    id: 4,
    title: "Business Proposal Writing",
    type: "PDF",
    resourceUrl: "/files/proposal.pdf",
    createdAt: "2025-06-08",
    category: "Business",
    level: "Intermediate",
    instructor: "Mary Joseph",
    startDate: "2024-08-15",
    endDate: "2024-10-15",
    status: "ONGOING",

  },
];

// ================== MASWALI ==================
export const maswali = [
  {
    id: 1,
    question: "Ninawezaje kuomba internship?",
    status: "PENDING",
    askedBy: "Asha Mrema",
    category: "Fursa",
    answers: 0,
    createdAt: "2025-06-15",
  },
  {
    id: 2,
    question: "Ninawezaje kuomba grant za vijana?",
    askedBy: "Kelvin Juma",
    category: "Fursa",
    answers: 2,
    status: "ANSWERED",
    createdAt: "2024-06-20",
  },
  {
    id: 3,
    question: "Je, mafunzo ni bure?",
    status: "ANSWERED",
    askedBy: "Juma Said",
    category: "Mafunzo",
    answers: 2,
    createdAt: "2025-06-10",
  },
  {
    id: 4,
    question: "Ni mafunzo gani yanapatikana online?",
    askedBy: "Asha Salum",
    category: "Mafunzo",
    answers: 0,
    status: "PENDING",
    createdAt: "2024-06-22",
  },
];
